# Generated by Django 5.2 on 2025-05-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_generic', models.BooleanField(default=False, help_text='Whether this is a generic email (e.g. no-reply@company.com)')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmail_label_id', models.CharField(max_length=100, unique=True)),
                ('label_knowledge', models.TextField(blank=True, help_text='Context for AI to understand this label', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('knowledge', models.TextField(blank=True, help_text='Context for AI to understand this contact', null=True)),
                ('emails', models.ManyToManyField(related_name='contacts', to='core.emailaddress')),
            ],
        ),
        migrations.CreateModel(
            name='EmailString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_string', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('snippet', models.TextField()),
                ('cc_str', models.ManyToManyField(related_name='cc_emails', to='core.emailstring')),
                ('sender_str', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_emails', to='core.emailstring')),
                ('to_str', models.ManyToManyField(related_name='to_emails', to='core.emailstring')),
                ('labels', models.ManyToManyField(blank=True, to='core.label')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('labels', models.ManyToManyField(blank=True, to='core.label')),
                ('last_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_email', to='core.email')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thread'),
        ),
        migrations.CreateModel(
            name='ThreadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.email')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thread')),
            ],
        ),
    ]
